# Site
name: "Gluten Free Ideas"
title: "Gluten Free Ideas"
description: "A site to learn how to cook easy GF recipes."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: /gfideas
google_analytics: 'UA-46278016-1'
disqus: 'gfideas'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vivi:
    name: Viviana Burijson
    display_name: Vivi
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: vivi-gf@gmail.com
    web: https://www.gfideas.com
    twitter: https://twitter.com/gf-ideas
    description: "Author of GF Ideas."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
